version: '3'

networks:
  default:
    external:
      name: knowledge-net

services:
  mongodb:
    image: mongo
    container_name: mongo-container
    ports:
      - 27017:27017
    hostname: demo.mongodb.com
    volumes:
      - $HOME/projects/search-data/db:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: search-container
    ports:
      - 9200:9200
      - 9300:9300
    hostname: demo.elasticsearch.com
    environment:
      - discovery.type=single-node
    volumes:
      - $HOME/projects/mongo-data/db:/data/db
  elasticsearchHQ:
    image: elastichq/elasticsearch-hq
    container_name: searchHq-container
    ports:
      - 5000:5000
    hostname: demo.elasticsearch-hq.com
